[package]
name = "kda-tools"
version = "0.1.0"
authors = ["Josh Vander Hook <josh@vanderhook.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra="0.25.0"
